# Generated by Django 4.1.7 on 2023-03-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('brand_name', models.CharField(max_length=200)),
                ('product_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'data_article',
            },
        ),
    ]
