#!/bin/sh
set -e

echo "*** CREATING DATABASE ***"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_NAME" <<-EOSQL
	ALTER USER $POSTGRES_USER PASSWORD '$POSTGRES_PASSWORD';
	CREATE DATABASE $POSTGRES_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_NAME TO $POSTGRES_USER;
EOSQL